# Generated by Django 5.1.3 on 2024-12-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comision',
            name='Curso',
        ),
        migrations.CreateModel(
            name='Liquidaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.PositiveIntegerField()),
                ('Consorcio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dni', models.IntegerField()),
                ('Nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.liquidaciones')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Comision',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
