# Generated by Django 5.1.3 on 2025-02-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
    ]
