# Generated by Django 5.1.3 on 2024-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_unidades_nombre_rename_dni_unidades_piso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='periodo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('consorcio', 'periodo')},
        ),
    ]
