# Generated by Django 5.1.4 on 2024-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_liquidacion_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='clave_del_consorcio',
            field=models.CharField(default='valor_default', max_length=255),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='cuit',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consorcio',
            name='localidad',
            field=models.CharField(default='caba', max_length=255),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='provincia',
            field=models.CharField(default='Buenos Aires', max_length=255),
        ),
        migrations.AlterField(
            model_name='consorcio',
            name='domicilio',
            field=models.CharField(max_length=255),
        ),
    ]
