# Generated by Django 5.1.3 on 2025-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_unidades_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('rubro', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
