# Generated by Django 5.1.4 on 2025-01-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=12)),
                ('concepto', models.CharField(max_length=1000)),
                ('columna', models.CharField(max_length=150)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rubro', models.IntegerField(choices=[(1, 'Rubro 1'), (2, 'Rubro 2'), (3, 'Rubro 3'), (4, 'Rubro 4'), (5, 'Rubro 5'), (6, 'Rubro 6'), (7, 'Rubro 7'), (8, 'Rubro 8'), (9, 'Rubro 9'), (10, 'Rubro 10')])),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='tienda.proveedor')),
            ],
        ),
    ]
