# Generated by Django 5.1.4 on 2025-01-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_gastos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'ordering': ['-fecha'], 'verbose_name': 'gasto', 'verbose_name_plural': 'gastos'},
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='rubro',
        ),
        migrations.AddField(
            model_name='gastos',
            name='consorcio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='tienda.consorcio'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_proveedor', to='tienda.proveedor'),
        ),
    ]
