# Generated by Django 5.1.3 on 2025-01-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_gastos_options_remove_gastos_rubro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='rubro',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gastos',
            name='factura',
            field=models.CharField(max_length=22),
        ),
    ]
