# Generated by Django 5.1.4 on 2025-01-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_gastos_rubro_alter_gastos_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'verbose_name': 'gasto', 'verbose_name_plural': 'gastos'},
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='fecha',
        ),
    ]
