# Generated by Django 5.1.4 on 2025-01-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_gastos_options_remove_gastos_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastos',
            old_name='columna',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='gastos',
            old_name='factura',
            new_name='comprobante',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='proveedor',
        ),
    ]
