# Generated by Django 5.1.3 on 2025-01-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='proveedor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
