# Generated by Django 5.1.3 on 2025-01-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_gastos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='tienda.proveedor'),
        ),
    ]
